version: "3.3"

services:
  backend:
    container_name: app_backend
    depends_on:
      - db
    volumes:
      - ./app_backend:/home/app
    working_dir: /home/app
    build: ./build/backend
    ports:
      - "3001:80"
  db:
    container_name: app_db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    cap_add:
      - SYS_NICE
    volumes:
      - ./.database:/var/lib/mysql #NOTE: temporarily for developing purpose
  pma:
    container_name: app_db_pma
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "3002:80"
    environment:
      PMA_HOST: db
      PMA_USER: app
      PMA_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
#  frontend:
#    container_name: app_frontend
#    depends_on:
#      - backend
#    volumes:
#      - ./app_frontend:/home/app #NOTE: temporarily for developing purpose
#    working_dir: /home/app
#    build: ./build/frontend
#    ports:
#      - "3000:80"

